# Generated by Django 5.0.6 on 2024-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_id',
            new_name='login_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='login_id',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='usertype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
